// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyButSflVpDkWzLgIubFMgtCsluJUa87_IM',
    appId: '1:961658686851:web:6b754dd05018dfae4a3ab6',
    messagingSenderId: '961658686851',
    projectId: 'fir-flutter-codelab-70fb2',
    authDomain: 'fir-flutter-codelab-70fb2.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-70fb2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkwC7ZgIHDk0is5bwjDln2rIT5vwdYlbk',
    appId: '1:961658686851:android:435a0b374aa367864a3ab6',
    messagingSenderId: '961658686851',
    projectId: 'fir-flutter-codelab-70fb2',
    storageBucket: 'fir-flutter-codelab-70fb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABw6VDNwAfUlxib1AkOnOSK1JChvnqaXQ',
    appId: '1:961658686851:ios:a11b4178c838cb9e4a3ab6',
    messagingSenderId: '961658686851',
    projectId: 'fir-flutter-codelab-70fb2',
    storageBucket: 'fir-flutter-codelab-70fb2.appspot.com',
    iosClientId: '961658686851-1qprplbbpmi874cqm5lkqi8ilkr4qlce.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABw6VDNwAfUlxib1AkOnOSK1JChvnqaXQ',
    appId: '1:961658686851:ios:a11b4178c838cb9e4a3ab6',
    messagingSenderId: '961658686851',
    projectId: 'fir-flutter-codelab-70fb2',
    storageBucket: 'fir-flutter-codelab-70fb2.appspot.com',
    iosClientId: '961658686851-1qprplbbpmi874cqm5lkqi8ilkr4qlce.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
